# Generated by Django 3.0.8 on 2020-07-13 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('nickname', models.CharField(max_length=50)),
                ('agree_years', models.BooleanField(default=0)),
                ('agree_terms', models.BooleanField(default=0)),
                ('agree_policy', models.BooleanField(default=0)),
                ('agree_promotion', models.BooleanField(default=0)),
                ('homepage', models.CharField(max_length=200)),
                ('gender', models.BooleanField(default=0)),
                ('introduction', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='profile/image')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.User')),
            ],
            options={
                'db_table': 'points',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=150)),
                ('period', models.DateField()),
                ('condition', models.CharField(max_length=150)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.User')),
            ],
            options={
                'db_table': 'coupons',
            },
        ),
    ]
